import type { Metadata } from "next";
import Image from "next/image";
import { getPublishedTestimonials } from "@/lib/supabase/queries";
import TestimonialsStrip from "@/components/home/TestimonialsStrip";
import { Award, Heart, Compass, Users } from "lucide-react";

export const revalidate = 3600;

export const metadata: Metadata = {
  title: "About Us — Our Story & Philosophy",
  description:
    "Founded in 2018, ENJOY Holidays has been crafting premium travel experiences across India. Meet our team, read our story, and discover what makes us different.",
};

const values = [
  { icon: Heart, title: "Crafted with Care", desc: "Every itinerary is handpicked — not generated by an algorithm. We've been to every destination we sell." },
  { icon: Compass, title: "Journey-First Thinking", desc: "We obsess over the experience between destinations, not just the highlights. The drive, the chai stop, the scenic detour — it all matters." },
  { icon: Users, title: "Personal Relationships", desc: "Your holiday manager stays with you end-to-end. One point of contact, zero chaos." },
  { icon: Award, title: "No Hidden Surprises", desc: "Transparent pricing, detailed itineraries, and honest advice — even if it means recommending a cheaper option." },
];

export default async function AboutPage() {
  const testimonials = await getPublishedTestimonials();

  return (
    <>
      {/* Header */}
      <section
        className="pt-36 pb-16 grain-overlay"
        style={{ background: "var(--color-deep-teal)" }}
        aria-labelledby="about-page-heading"
      >
        <div className="container-site max-w-4xl">
          <span className="label text-[var(--color-secondary-light)] mb-3 block">✦ Who We Are</span>
          <h1 id="about-page-heading" className="display-xl text-white mb-5">
            We Don&apos;t Sell Packages. <br />
            <span className="italic text-[var(--color-secondary-light)]">We Craft Memories.</span>
          </h1>
          <p className="body-lg text-white/70 max-w-2xl">
            ENJOY Holidays was born from a simple belief: that travel should feel personal, not packaged. Founded in 2018 in Kochi, we&apos;ve spent six years perfecting the art of the Indian holiday.
          </p>
        </div>
      </section>

      {/* Story section */}
      <section className="py-20" aria-labelledby="story-heading">
        <div className="container-site max-w-5xl">
          <div className="grid md:grid-cols-2 gap-12 items-center">
            <div>
              <span className="label text-[var(--color-primary)] mb-3 block">✦ Our Story</span>
              <h2 id="story-heading" className="display-lg text-[var(--color-text-primary)] mb-5">
                From a Single Trip to 500+ Happy Travellers
              </h2>
              <div className="flex flex-col gap-4 body-md text-[var(--color-text-secondary)]">
                <p>
                  It started with a road trip gone wrong — a &quot;packaged tour&quot; that turned out to be a bus full of strangers, rushed sightseeing, and meals that could&apos;ve been anywhere. Our founder, Arun Nair, came back from that trip and decided there had to be a better way.
                </p>
                <p>
                  He started ENJOY Holidays with one rule: every package must be one he&apos;d be proud to take his own family on. Six years later, that rule still holds.
                </p>
                <p>
                  Today we&apos;re a team of 12 travel obsessives, with contacts at the best homestays, the most authentic local guides, and the secret sunrise spots that TripAdvisor doesn&apos;t know about — yet.
                </p>
              </div>
            </div>

            {/* Polaroid-style photo grid */}
            <div className="grid grid-cols-2 gap-4">
              <div className="polaroid">
                <div className="relative aspect-square overflow-hidden rounded-sm">
                  <Image
                    src="https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?w=400&q=80"
                    alt="Kerala backwaters"
                    fill
                    className="object-cover"
                    sizes="200px"
                  />
                </div>
                <p className="text-center text-xs text-gray-500 mt-3 font-sans">Alleppey, 2022</p>
              </div>
              <div className="polaroid polaroid-alt mt-8">
                <div className="relative aspect-square overflow-hidden rounded-sm">
                  <Image
                    src="https://images.unsplash.com/photo-1582510003544-4d00b7f74220?w=400&q=80"
                    alt="Coorg highlands"
                    fill
                    className="object-cover"
                    sizes="200px"
                  />
                </div>
                <p className="text-center text-xs text-gray-500 mt-3 font-sans">Coorg, 2023</p>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* Values */}
      <section
        className="py-16"
        style={{ background: "var(--color-surface-alt)" }}
        aria-labelledby="values-heading"
      >
        <div className="container-site">
          <div className="text-center mb-12">
            <span className="label text-[var(--color-primary)] mb-2 block">✦ What We Stand For</span>
            <h2 id="values-heading" className="display-lg text-[var(--color-text-primary)]">
              Our <span className="italic text-[var(--color-primary)]">Values</span>
            </h2>
          </div>
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
            {values.map(({ icon: Icon, title, desc }) => (
              <div
                key={title}
                className="p-6 rounded-2xl bg-white"
                style={{ border: "1px solid var(--color-border)" }}
              >
                <div
                  className="w-12 h-12 rounded-xl flex items-center justify-center mb-4"
                  style={{ background: "rgba(212,92,51,0.08)" }}
                >
                  <Icon size={22} style={{ color: "var(--color-primary)" }} />
                </div>
                <h3 className="font-bold text-[var(--color-text-primary)] mb-2 text-sm">{title}</h3>
                <p className="text-sm text-[var(--color-text-muted)] leading-relaxed">{desc}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Testimonials */}
      <TestimonialsStrip testimonials={testimonials} />

      <div className="h-20 md:h-0 block md:hidden" aria-hidden="true" />
    </>
  );
}
